### ISSUE TITLE
Flow app printing a lot of error messages

### ISSUE THREAD

**Issue by ksuprynowicz** [overte-org/community-apps#77]
```
[03/30 21:34:50] [CRITICAL] [overte.scriptengine]     at Function.keys (<anonymous>)
[03/30 21:34:50] [CRITICAL] [overte.scriptengine]     at https://docs.overte.org/_static/resources/script/flow/flowAppCpp/flowAppCpp.js:434:37
[03/30 21:34:50] [CRITICAL] [overte.scriptengine] This provided: 0
[03/30 21:34:50] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught TypeError: Cannot convert undefined or null to object" "[Error in signal proxy]"  at line  434 , column  36 Backtrace: ("TypeError: Cannot convert undefined or null to object", "    at Function.keys (<anonymous>)", "    at https://docs.overte.org/_static/resources/script/flow/flowAppCpp/flowAppCpp.js:434:37")
[03/30 21:34:50] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
[03/30 21:34:50] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught TypeError: Cannot convert undefined or null to object" "[Error in signal proxy]"  at line  434 , column  36 Backtrace: ("TypeError: Cannot convert undefined or null to object", "    at Function.keys (<anonymous>)", "    at https://docs.overte.org/_static/resources/script/flow/flowAppCpp/flowAppCpp.js:434:37")
```

**Comment by LimeProgramming** [comment]
take the prints commands out, it'll be fine

**Comment by LimeProgramming** [comment]
> take the prints commands out, it'll be fine

if an error prints but nothing breaks, does the error exist?
