### ISSUE TITLE
[FlowApp] Uncaught exception

### ISSUE THREAD

**Issue by Armored-Dragon** [overte-org/community-apps#86]
```
run ---------- UNCAUGHT EXCEPTION --------
[05/24 17:44:30] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught TypeError: Cannot convert undefined or null to object" "[Error in signal proxy]"  at line  434 , column  36 Backtrace: ("TypeError: Cannot convert undefined or null to object", "    at Function.keys (<anonymous>)", "    at https://docs.overte.org/en/latest/_static/resources/script/flow/flowAppCpp/flowAppCpp.js:434:37")
[05/24 17:44:30] [CRITICAL] [overte.scriptengine] [flowAppCpp.js] Signal proxy ScriptManagerScriptingInterface::update connection call failed: "failed on line 434 column 36 with message: "Uncaught TypeError: Cannot convert undefined or null to object" backtrace: TypeError: Cannot convert undefined or null to object
[05/24 17:44:30] [CRITICAL] [overte.scriptengine]     at Function.keys (<anonymous>)
[05/24 17:44:30] [CRITICAL] [overte.scriptengine]     at https://docs.overte.org/en/latest/_static/resources/script/flow/flowAppCpp/flowAppCpp.js:434:37
[05/24 17:44:30] [CRITICAL] [overte.scriptengine] This provided: 0
[05/24 17:44:30] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught TypeError: Cannot convert undefined or null to object" "[Error in signal proxy]"  at line  434 , column  36 Backtrace: ("TypeError: Cannot convert undefined or null to object", "    at Function.keys (<anonymous>)", "    at https://docs.overte.org/en/latest/_static/resources/script/flow/flowAppCpp/flowAppCpp.js:434:37")
```
When trying to load a specific avatar, this exception is being spammed into the console and the avatar fails to load.
This exception is likely a result of the load failure and not the other way around?

For a avatar sample please ask me, @Armored-Dragon

**Comment by Armored-Dragon** [comment]
Closing as duplicate of #77
