### ISSUE TITLE
[Nametags.js] Error spam when going into first person

### ISSUE THREAD

**Issue by Armored-Dragon** [overte-org/community-apps#87]
When nametags.js is in an error state, this logspam can occur when moving into first person.
Potentially related to #82. When going into first person your nametag gets removed.
The following is spammed into the log:

```javascript
[06/05 16:19:16] [WARNING] [overte.scriptengine] run ---------- UNCAUGHT EXCEPTION --------
[06/05 16:19:16] [WARNING] [overte.scriptengine] runInThread Exception: "Uncaught TypeError: Cannot read properties of undefined (reading 'text')" "[Error in signal proxy]"  at line  116 , column  51 Backtrace: ("TypeError: Cannot read properties of undefined (reading 'text')", "    at _removeUser (https://more.overte.org/applications/nametags/nametags.js:116:52)", "    at _adjustNametags (https://more.overte.org/applications/nametags/nametags.js:124:49)")
[06/05 16:19:16] [DEBUG] [overte.scriptengine] [nametags.js] Deleting {} nametag
[06/05 16:19:16] [CRITICAL] [overte.scriptengine] [nametags.js] Signal proxy ScriptManagerScriptingInterface::update connection call failed: "failed on line 116 column 51 with message: "Uncaught TypeError: Cannot read properties of undefined (reading 'text')" backtrace: TypeError: Cannot read properties of undefined (reading 'text')
[06/05 16:19:16] [CRITICAL] [overte.scriptengine]     at _removeUser (https://more.overte.org/applications/nametags/nametags.js:116:52)
[06/05 16:19:16] [CRITICAL] [overte.scriptengine]     at _adjustNametags (https://more.overte.org/applications/nametags/nametags.js:124:49)
[06/05 16:19:16] [CRITICAL] [overte.scriptengine] This provided: 0
[06/05 16:19:16] [DEBUG] [overte.scriptengine.v8] Emitting exception: Exception: "Uncaught TypeError: Cannot read properties of undefined (reading 'text')" "[Error in signal proxy]"  at line  116 , column  51 Backtrace: ("TypeError: Cannot read properties of undefined (reading 'text')", "    at _removeUser (https://more.overte.org/applications/nametags/nametags.js:116:52)", "    at _adjustNametags (https://more.overte.org/applications/nametags/nametags.js:124:49)")
```

**Comment by Armored-Dragon** [comment]
This is the same issue but a different cause.
Closing as duplicate of #82.
